name: cognitive-swarm
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Interpréteur Python ---
  - python=3.11

  # --- Gestion des dépendances et exécution ---
  - pip 

  # --- Configuration et Utilitaires ---
  - pydantic
  - pydantic-settings
  - python-dotenv

  # --- Traitement des Données et PDF ---
  - arxiv
  - pymupdf # Pour PyMuPDF (parsing PDF)
  - pandas
  - numpy

  # --- LLMs, Embeddings, Tokenisation ---
  - openai 
  - tiktoken

  # --- Frameworks LangChain & LlamaIndex ---
  - langchain-core
  - langchain-openai
  - langchain-community
  - langchain-ollama
  - langchain-huggingface 
  - langchain 
  - langgraph
  
  - llama-index-core 
  
  # --- Base de Données (MongoDB) ---
  - pymongo 
  - motor 

  # --- Évaluation et Logging de Métriques ---
  - wandb 

  # --- Web API (FastAPI) --- # <<< AJOUTÉ ICI
  - fastapi
  - uvicorn

  # --- Développement (Notebooks, etc.) ---
  - jupyter 
  - ipykernel 

  # --- Paquets à installer via Pip ---
  - pip:
    - llama-index-vector-stores-mongodb
    - llama-index-embeddings-openai
    - llama-index-embeddings-huggingface # <<< NOUVELLE DÉPENDANCE AJOUTÉE ICI
    - llama-index-embeddings-ollama      # <<< AJOUT PRÉVENTIF POUR OLLAMA EMBEDDINGS LlamaIndex
    - crewai
    # - crewai-tools # Optionnel